"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-22 00:12:50.471120

Autogenerate is a drafting aid, not trusted output (docs/04 §3.7): it does not reliably
detect CHECK-constraint changes and will emit a non-batch ALTER that works on Postgres
and fails on SQLite. Review and edit every revision by hand.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=True),
        sa.Column("actor_sub", sa.Text(), nullable=False),
        sa.Column("actor_email", sa.Text(), nullable=False),
        sa.Column("actor_groups", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('allowed', 'denied', 'failed')", name=op.f("ck_audit_log_outcome")
        ),
        sa.PrimaryKeyConstraint("audit_id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("idx_audit_actor", ["actor_sub", "occurred_at"], unique=False)
        batch_op.create_index("idx_audit_target", ["target_type", "target_id"], unique=False)
        batch_op.create_index("idx_audit_trace", ["trace_id"], unique=False)

    op.create_table(
        "customer",
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("date_of_birth", sa.Text(), nullable=False),
        sa.Column("address_line1", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), server_default="SG", nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("preferred_lang", sa.Text(), server_default="en", nullable=False),
        sa.Column("risk_flag", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'closed')", name=op.f("ck_customer_status")
        ),
        sa.CheckConstraint(
            "tier IN ('standard', 'silver', 'gold', 'platinum')", name=op.f("ck_customer_tier")
        ),
        sa.CheckConstraint("risk_flag IN (0,1)", name=op.f("ck_customer_risk_flag")),
        sa.PrimaryKeyConstraint("customer_id", name=op.f("pk_customer")),
        sa.UniqueConstraint("email", name=op.f("uq_customer_email")),
    )
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.create_index("idx_customer_email", ["email"], unique=False)
        batch_op.create_index("idx_customer_name", ["full_name"], unique=False)

    op.create_table(
        "kb_article",
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("applies_to", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("article_id", name=op.f("pk_kb_article")),
    )
    op.create_table(
        "policy",
        sa.Column("policy_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("product", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("premium_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.Text(), server_default="SGD", nullable=False),
        sa.Column("effective_from", sa.Text(), nullable=False),
        sa.Column("effective_to", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "product IN ('motor', 'health', 'travel', 'home', 'life')",
            name=op.f("ck_policy_product"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'lapsed', 'cancelled', 'pending')", name=op.f("ck_policy_status")
        ),
        sa.CheckConstraint("premium_cents >= 0", name=op.f("ck_policy_premium_cents")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.customer_id"],
            name=op.f("fk_policy_customer_id_customer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("policy_id", name=op.f("pk_policy")),
    )
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.create_index("idx_policy_customer", ["customer_id"], unique=False)

    op.create_table(
        "claim",
        sa.Column("claim_id", sa.String(), nullable=False),
        sa.Column("policy_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("failure_code", sa.Text(), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.Text(), server_default="SGD", nullable=False),
        sa.Column("incident_date", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.Text(), nullable=True),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "channel IN ('web', 'mobile', 'agent', 'broker')", name=op.f("ck_claim_channel")
        ),
        sa.CheckConstraint(
            "failure_code IN ('DOC_MISSING', 'DOC_UNREADABLE', 'POLICY_LAPSED', 'DUPLICATE', 'VALIDATION_ERROR', 'GATEWAY_TIMEOUT', 'LIMIT_EXCEEDED')",
            name=op.f("ck_claim_failure_code"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'submission_failed', 'under_review', 'approved', 'rejected', 'paid', 'withdrawn')",
            name=op.f("ck_claim_status"),
        ),
        sa.CheckConstraint("amount_cents >= 0", name=op.f("ck_claim_amount_cents")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.customer_id"],
            name=op.f("fk_claim_customer_id_customer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.policy_id"],
            name=op.f("fk_claim_policy_id_policy"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("claim_id", name=op.f("pk_claim")),
    )
    with op.batch_alter_table("claim", schema=None) as batch_op:
        batch_op.create_index("idx_claim_customer", ["customer_id", "created_at"], unique=False)
        batch_op.create_index("idx_claim_status", ["status"], unique=False)

    op.create_table(
        "case",
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("claim_id", sa.String(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=True),
        sa.Column("escalated_to", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "category IN ('claim_issue', 'billing', 'coverage_query', 'complaint', 'policy_change', 'technical')",
            name=op.f("ck_case_category"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'critical')", name=op.f("ck_case_priority")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'investigating', 'pending_customer', 'escalated', 'resolved', 'closed')",
            name=op.f("ck_case_status"),
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.claim_id"],
            name=op.f("fk_case_claim_id_claim"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.customer_id"],
            name=op.f("fk_case_customer_id_customer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_case")),
    )
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.create_index("idx_case_customer", ["customer_id", "opened_at"], unique=False)
        batch_op.create_index("idx_case_status", ["status", "priority"], unique=False)

    op.create_table(
        "case_event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.case_id"],
            name=op.f("fk_case_event_case_id_case"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_case_event")),
    )
    with op.batch_alter_table("case_event", schema=None) as batch_op:
        batch_op.create_index("idx_case_event_case", ["case_id", "occurred_at"], unique=False)

    op.create_table(
        "interaction",
        sa.Column("interaction_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=True),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("sentiment", sa.Text(), nullable=False),
        sa.Column("handled_by", sa.Text(), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "channel IN ('voice', 'chat', 'email', 'callback')", name=op.f("ck_interaction_channel")
        ),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound')", name=op.f("ck_interaction_direction")
        ),
        sa.CheckConstraint(
            "sentiment IN ('positive', 'neutral', 'negative')",
            name=op.f("ck_interaction_sentiment"),
        ),
        sa.CheckConstraint("duration_sec >= 0", name=op.f("ck_interaction_duration_sec")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.case_id"],
            name=op.f("fk_interaction_case_id_case"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.customer_id"],
            name=op.f("fk_interaction_customer_id_customer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("interaction_id", name=op.f("pk_interaction")),
    )
    with op.batch_alter_table("interaction", schema=None) as batch_op:
        batch_op.create_index("idx_interaction_case", ["case_id"], unique=False)
        batch_op.create_index(
            "idx_interaction_customer", ["customer_id", "occurred_at"], unique=False
        )

    op.create_table(
        "ticket",
        sa.Column("ticket_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("assignee", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("created_via", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "category IN ('claim_issue', 'billing', 'coverage_query', 'complaint', 'policy_change', 'technical')",
            name=op.f("ck_ticket_category"),
        ),
        sa.CheckConstraint(
            "created_via IN ('assistant', 'agent_manual', 'system')",
            name=op.f("ck_ticket_created_via"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'critical')", name=op.f("ck_ticket_priority")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'pending', 'resolved', 'closed')",
            name=op.f("ck_ticket_status"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["case.case_id"], name=op.f("fk_ticket_case_id_case"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.customer_id"],
            name=op.f("fk_ticket_customer_id_customer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ticket_id", name=op.f("pk_ticket")),
    )
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.create_index("idx_ticket_case", ["case_id"], unique=False)
        batch_op.create_index("idx_ticket_customer", ["customer_id", "created_at"], unique=False)

    op.create_table(
        "ticket_event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.ticket_id"],
            name=op.f("fk_ticket_event_ticket_id_ticket"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_ticket_event")),
    )
    with op.batch_alter_table("ticket_event", schema=None) as batch_op:
        batch_op.create_index("idx_ticket_event_ticket", ["ticket_id", "occurred_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ticket_event", schema=None) as batch_op:
        batch_op.drop_index("idx_ticket_event_ticket")

    op.drop_table("ticket_event")
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_index("idx_ticket_customer")
        batch_op.drop_index("idx_ticket_case")

    op.drop_table("ticket")
    with op.batch_alter_table("interaction", schema=None) as batch_op:
        batch_op.drop_index("idx_interaction_customer")
        batch_op.drop_index("idx_interaction_case")

    op.drop_table("interaction")
    with op.batch_alter_table("case_event", schema=None) as batch_op:
        batch_op.drop_index("idx_case_event_case")

    op.drop_table("case_event")
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.drop_index("idx_case_status")
        batch_op.drop_index("idx_case_customer")

    op.drop_table("case")
    with op.batch_alter_table("claim", schema=None) as batch_op:
        batch_op.drop_index("idx_claim_status")
        batch_op.drop_index("idx_claim_customer")

    op.drop_table("claim")
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.drop_index("idx_policy_customer")

    op.drop_table("policy")
    op.drop_table("kb_article")
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_index("idx_customer_name")
        batch_op.drop_index("idx_customer_email")

    op.drop_table("customer")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("idx_audit_trace")
        batch_op.drop_index("idx_audit_target")
        batch_op.drop_index("idx_audit_actor")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
