"""vector search tables

Revision ID: 0002_vector_tables
Revises: 0001_initial
Create Date: 2026-08-22

docs/13 §3.3. Written by hand rather than autogenerated: ``vec0`` virtual tables are
invisible to SQLAlchemy's metadata comparison, so autogenerate would propose dropping
them on every subsequent run.

**This revision always applies, but its virtual tables are conditional.** ``vec_meta``
is a plain table and is always created; the ``vec_*`` virtual tables are created only
when the ``sqlite-vec`` extension loads. That keeps the revision graph linear so
``alembic_version`` reaches head in both build variants (docs/13 §3.6) — the readiness
probe checks for head, and a keyword-only image must still be ready.
"""

from __future__ import annotations

import logging
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.engine import load_vector_extension

revision: str = "0002_vector_tables"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

log = logging.getLogger("alembic.runtime.migration")

EMBEDDING_DIMENSIONS = 768


def _vector_tables_available() -> bool:
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        return False
    raw = bind.connection.driver_connection
    return load_vector_extension(raw)


def upgrade() -> None:
    op.create_table(
        "vec_meta",
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("indexed_at", sa.Text(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("table_name", name=op.f("pk_vec_meta")),
    )

    if not _vector_tables_available():
        log.info("sqlite-vec unavailable; vec_meta created, virtual tables skipped")
        return

    for table, key in (("vec_interaction", "interaction_id"), ("vec_kb", "article_id")):
        op.execute(
            f"CREATE VIRTUAL TABLE {table} USING vec0("
            f"{key} TEXT PRIMARY KEY, embedding FLOAT[{EMBEDDING_DIMENSIONS}])"
        )


def downgrade() -> None:
    for table in ("vec_kb", "vec_interaction"):
        op.execute(f"DROP TABLE IF EXISTS {table}")
    op.drop_table("vec_meta")
