"""conversation threads

Revision ID: 0003_threads
Revises: 0002_vector_tables
Create Date: 2026-08-22 01:07:51.733262

Autogenerate is a drafting aid, not trusted output (docs/04 §3.7): it does not reliably
detect CHECK-constraint changes and will emit a non-batch ALTER that works on Postgres
and fails on SQLite. Review and edit every revision by hand.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_threads"
down_revision: str | None = "0002_vector_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread",
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("owner_sub", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("subject_customer_id", sa.Text(), nullable=True),
        sa.Column("message_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_thread")),
    )
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.create_index("idx_thread_owner", ["owner_sub", "updated_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_index("idx_thread_owner")

    op.drop_table("thread")
    # ### end Alembic commands ###
